# Tensor Introduction

We will revisit the basics of tensors, how to convert numpy to tensor objects, and more 

* What is a tensor? (in maths)

    * It describes a multilinear relantionship between algebraic objects related to the same vector space.
    

* What is a tensor? (in DL)

    * Is basically the same as a numpy array, a generic n-dimensional array to be used for computation, the biggest diference between a *numpy array* and a *pytorch tensor* is that **the latest can run on a GPU**.

## Import libraries

In [1]:
import torch 

## Creating tensors
* Create an empty tensor:

In [2]:
x = torch.empty(3) # 1 row , 3 col
print(x)

tensor([1.7227e+25, 1.2160e-38, 1.0332e+18])


* We can specify the dimensions of our empty tensor:

In [3]:
x = torch.empty(2,3) # 2 row , 3 col
print(x)

tensor([[ 4.8684e-36,  0.0000e+00, -4.3868e+31],
        [ 4.5567e-41,  8.9683e-44,  0.0000e+00]])


* We can create a tensor with random numbers, zeros, ones or specific list (check the documentation):

In [4]:
x = torch.rand(2,2)
print(x)

tensor([[0.5483, 0.5391],
        [0.0130, 0.2299]])


In [5]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [6]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
x = torch.tensor([2,3,1,0.5])
print(x)

tensor([2.0000, 3.0000, 1.0000, 0.5000])


Inspecting properties, dtype, size, etc:

In [8]:
print(x.dtype)

torch.float32


In [9]:
x = torch.ones(2,2, dtype=torch.int)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [10]:
print(x.dtype)

torch.int32


In [11]:
print(x.size())

torch.Size([2, 2])


## Tensor basic operations:

In [12]:
x = torch.rand(2,2)
y = torch.rand(2,2)

* element wise addition, etc.

In [13]:
z = x + y
print(z)

tensor([[0.8883, 1.2151],
        [0.6765, 1.1233]])


In [14]:
z = torch.add(x,y)
print(z)

tensor([[0.8883, 1.2151],
        [0.6765, 1.1233]])


inplace addition (this will add x to y and assign that to y):
* Any operation can do this

In [15]:
y.add_(x)
print(y)

tensor([[0.8883, 1.2151],
        [0.6765, 1.1233]])


Check the documentation for other basic operators, $-,*,/$ == `.sub,.mul,.div`

## Slicing

Basically is the same as numpy

In [16]:
x = torch.rand(3,3)
print(x)
print(f"selecting all rows, first column: {x[:,0]}")

tensor([[0.5801, 0.9209, 0.7588],
        [0.3126, 0.9411, 0.1569],
        [0.1624, 0.1705, 0.1413]])
selecting all rows, first column: tensor([0.5801, 0.3126, 0.1624])


If we want to extract the actual value from a tensor of a given item we need to use `.item()` : 

* only usable with one value tensor

In [17]:
print(x[0,0])
print(x[0,0].item())

tensor(0.5801)
0.5801304578781128


## Reshaping

In [18]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.7881, 0.7117, 0.6396, 0.2348],
        [0.0316, 0.3167, 0.2224, 0.7648],
        [0.9648, 0.7068, 0.1535, 0.7075],
        [0.2641, 0.0735, 0.0151, 0.6578]])
tensor([0.7881, 0.7117, 0.6396, 0.2348, 0.0316, 0.3167, 0.2224, 0.7648, 0.9648,
        0.7068, 0.1535, 0.7075, 0.2641, 0.0735, 0.0151, 0.6578])


We can let pytorch to infer the remaining dimension (**super useful**) by using -1 in that dimension: 

In [19]:
x.view(-1,8)

tensor([[0.7881, 0.7117, 0.6396, 0.2348, 0.0316, 0.3167, 0.2224, 0.7648],
        [0.9648, 0.7068, 0.1535, 0.7075, 0.2641, 0.0735, 0.0151, 0.6578]])

In [20]:
x.view(-1,2)

tensor([[0.7881, 0.7117],
        [0.6396, 0.2348],
        [0.0316, 0.3167],
        [0.2224, 0.7648],
        [0.9648, 0.7068],
        [0.1535, 0.7075],
        [0.2641, 0.0735],
        [0.0151, 0.6578]])

## Importing and exporting from numpy

In [21]:
import numpy as np

a = torch.rand(3)
print(a)

tensor([0.4108, 0.8983, 0.7329])


converting tensor to numpy array:
* CAUTION: modifying one changes the other!! they share the location in memory!!!

In [22]:
b = a.numpy()
print(b)

[0.41083324 0.89829606 0.7328639 ]


numpy to tensor:

In [23]:
a = np.ones(3)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


## Devices in pytorch

* first we need to check if cuda is available

In [24]:
torch.cuda.is_available()

True

If it is available we can set up as our device

In [25]:
if torch.cuda.is_available():
    device = torch.device("cuda")

Then we specify in which device are located our tensors:

In [26]:
x = torch.ones(3,3,device = device)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


we can send our tensor again to cpu:

In [27]:
print(x.cpu())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [28]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [31]:
x = x.to("cpu")
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
