# Tensor Introduction

We will revisit the basics of tensors, how to convert numpy to tensor objects, and more 

* What is a tensor? (in maths)

    * It describes a multilinear relantionship between algebraic objects related to the same vector space.
    

* What is a tensor? (in DL)

    * Is basically the same as a numpy array, a generic n-dimensional array to be used for computation, the biggest diference between a *numpy array* and a *pytorch tensor* is that **the latest can run on a GPU**.

## Import libraries

In [2]:
import torch 

## Creating tensors
* Create an empty tensor:

In [3]:
x = torch.empty(3) # 1 row , 3 col
print(x)

tensor([ 5.6665e-05,  4.5586e-41, -1.6892e-26])


* We can specify the dimensions of our empty tensor:

In [4]:
x = torch.empty(2,3) # 2 row , 3 col
print(x)

tensor([[ 2.6504e-36,  0.0000e+00,  2.6487e-36],
        [ 0.0000e+00, -1.7267e+16,  1.3354e+13]])


* We can create a tensor with random numbers, zeros, ones or specific list (check the documentation):

In [5]:
x = torch.rand(2,2)
print(x)

tensor([[0.5926, 0.1390],
        [0.0147, 0.2313]])


In [6]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [7]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [8]:
x = torch.tensor([2,3,1,0.5])
print(x)

tensor([2.0000, 3.0000, 1.0000, 0.5000])


Inspecting properties, dtype, size, etc:

In [9]:
print(x.dtype)

torch.float32


In [10]:
x = torch.ones(2,2, dtype=torch.int)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [11]:
print(x.dtype)

torch.int32


In [12]:
print(x.size())

torch.Size([2, 2])


## Tensor basic operations:

In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)

* element wise addition, etc.

In [14]:
z = x + y
print(z)

tensor([[1.5040, 0.8820],
        [1.3865, 0.1099]])


In [15]:
z = torch.add(x,y)
print(z)

tensor([[1.5040, 0.8820],
        [1.3865, 0.1099]])


inplace addition (this will add x to y and assign that to y):
* Any operation can do this

In [16]:
y.add_(x)
print(y)

tensor([[1.5040, 0.8820],
        [1.3865, 0.1099]])


Check the documentation for other basic operators, $-,*,/$ == `.sub,.mul,.div`

## Slicing

Basically is the same as numpy

In [18]:
x = torch.rand(3,3)
print(x)
print(f"selecting all rows, first column: {x[:,0]}")

tensor([[0.2573, 0.5112, 0.8590],
        [0.9912, 0.9880, 0.0347],
        [0.4771, 0.6739, 0.8405]])
selecting all rows, first column: tensor([0.2573, 0.9912, 0.4771])


If we want to extract the actual value from a tensor of a given item we need to use `.item()` : 

* only usable with one value tensor

In [19]:
print(x[0,0])
print(x[0,0].item())

tensor(0.2573)
0.2573397159576416


## Reshaping

In [20]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.5672, 0.0638, 0.2083, 0.4464],
        [0.8295, 0.8181, 0.6987, 0.4695],
        [0.9983, 0.5582, 0.3904, 0.7359],
        [0.8254, 0.5352, 0.8482, 0.4558]])
tensor([0.5672, 0.0638, 0.2083, 0.4464, 0.8295, 0.8181, 0.6987, 0.4695, 0.9983,
        0.5582, 0.3904, 0.7359, 0.8254, 0.5352, 0.8482, 0.4558])


We can let pytorch to infer the remaining dimension (**super useful**) by using -1 in that dimension: 

In [21]:
x.view(-1,8)

tensor([[0.5672, 0.0638, 0.2083, 0.4464, 0.8295, 0.8181, 0.6987, 0.4695],
        [0.9983, 0.5582, 0.3904, 0.7359, 0.8254, 0.5352, 0.8482, 0.4558]])

In [25]:
x.view(-1,2)

tensor([[0.5672, 0.0638],
        [0.2083, 0.4464],
        [0.8295, 0.8181],
        [0.6987, 0.4695],
        [0.9983, 0.5582],
        [0.3904, 0.7359],
        [0.8254, 0.5352],
        [0.8482, 0.4558]])

## Importing and exporing from numpy

In [26]:
import numpy as np

a = torch.rand(3)
print(a)

tensor([0.6489, 0.3804, 0.1903])


converting tensor to numpy array:
* CAUTION: modifying one changes the other!! they share the location in memory!!!

In [27]:
b = a.numpy()
print(b)

[0.64894444 0.38040632 0.19031566]


numpy to tensor:

In [29]:
a = np.ones(3)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


## Devices in pytorch