# Tensor Introduction

We will revisit the basics of tensors, how to convert numpy to tensor objects, and more 

* What is a tensor? (in maths)

    * It describes a multilinear relantionship between algebraic objects related to the same vector space.
    

* What is a tensor? (in DL)

    * Is basically the same as a numpy array, a generic n-dimensional array to be used for computation, the biggest diference between a *numpy array* and a *pytorch tensor* is that **the latest can run on a GPU**.

## Import libraries

In [1]:
import torch 

* Create an empty tensor:

In [2]:
x = torch.empty(3) # 1 row , 3 col
print(x)

tensor([-4.1005e-35,  2.7564e+26,  1.2161e-38])


* We can specify the dimensions of our empty tensor:

In [3]:
x = torch.empty(2,3) # 2 row , 3 col
print(x)

tensor([[1.8598e-36, 0.0000e+00, 1.8575e-36],
        [0.0000e+00, 1.0361e+22, 2.6633e+36]])


* We can create a tensor with random numbers or zeros:

In [4]:
x = torch.rand(2,2)
print(x)

tensor([[0.0056, 0.9823],
        [0.1788, 0.1393]])


In [5]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])
